# See dependabot.yml reference https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "dev"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
    assignees:
      - "ryanberckmans"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "dev"
    versioning-strategy: "increase-if-necessary"
    labels:
      - "dependencies"
      - "npm"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
    assignees:
      - "ryanberckmans"
