name: setup
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3 # this action may be (is currently always) run in a context where the code is already checked out, but here we run actions/checkout to ensure this action is context-free and internally consistent
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: yarn
    - uses: actions/cache@v3
      id: install-cache
      with:
        path: node_modules/
        key: ${{ runner.os }}-install-${{ hashFiles('**/yarn.lock') }}
    - if: steps.install-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile --ignore-scripts
      shell: bash
