name: Verify build
description: Verify a build for which the git checkout has already been done. The git branch being verified is implicit based on which code has already been checked out.
runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup
    # TODO run tests
    - run: yarn lint
      shell: bash # NB when using a composite action type, it's necessary to set the shell (not sure why, and docs don't say), whereas you can use `run: yarn build` in a workflow without specifying the shell https://stackoverflow.com/a/71042698
    - run: yarn build:dev
      shell: bash
    - run: yarn build:prod-test
      shell: bash
    - run: yarn build
      shell: bash
