name: Build prod testnet
description: Run a production build in the context of a checked out codebase and node that's already been fully setup and verified and is ready to immediately run the build. This action owns the definition of a production build with testnet dependencies.
inputs:
  tag:
    description: 'Git tag to be used'
    required: true
runs:
  using: composite
  steps:
    - run: yarn build
      shell: bash # NB when using a composite action type, it's necessary to set the shell (not sure why, and docs don't say), whereas you can use `run: yarn build` in a workflow without specifying the shell https://stackoverflow.com/a/71042698
      env:
        REACT_APP_GIT_TAG: ${{ inputs.tag }}
        REACT_APP_ALCHEMY_API_KEY: ${{ secrets.REACT_APP_ALCHEMY_API_KEY }}
        REACT_APP_INFURA_API_KEY: ${{ secrets.REACT_APP_INFURA_API_KEY }}
        REACT_APP_WEB3AUTH_CLIENT_ID: ${{ secrets.REACT_APP_WEB3AUTH_CLIENT_ID_STAGING }}
        REACT_APP_WALLETCONNECT_PROJECT_ID: ${{ secrets.REACT_APP_WALLETCONNECT_PROJECT_ID_STAGING }}
    # uncomment this step to test source map detection and trigger a workflow failure:
    - run: touch ./packages/react-app/build/static/fake-source.map
      shell: bash
    - run: (find ./packages/react-app/build | grep "map$" || exit 0 && (echo "unexpectedly found a source map in the build directory, failing build" && exit 1);) # sanity check to ensure sourcemaps are disabled in deployments to avoid leaking our web src
      shell: bash
