# Auto-build the main branch and on success, publish a workflow-level
# "main-branch-build" github status check.
name: main branch build
on:
  push:
    branches:
      - main
jobs:
  verify-build:
    runs-on: ubuntu-latest
    steps:
      - uses: 3cities/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
        with:
          ref: main
      - uses: ./.github/actions/verify-build
  main-branch-build: # no-op job to force a workflow-level "main-branch-build" github status check to be published. Github automatically makes the result of each workflow job available as a status check.
    needs: [verify-build]
    runs-on: ubuntu-latest
    steps:
      - run: exit 0 # no-op because a job definition requires something to do, but all we want this job to do is publish a workflow-level github status check.
