name: dev branch build
on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # check out code for actions/setup
      - uses: ./.github/actions/setup
      - run: yarn build
        env:
          REACT_APP_GIT_TAG: dev
