name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.github-tag-action.outputs.new_tag }}
      changelog: ${{ steps.github-tag-action.outputs.changelog }}
    steps:
      - uses: actions/checkout@v3
      - name: Bump and tag
        id: github-tag-action
        uses: mathieudutour/github-tag-action@d745f2e74aaf1ee82e747b181f7a0967978abee0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: .*
          default_bump: patch
  release:
    needs: tag
    if: ${{ needs.tag.outputs.new_tag != null }}
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - run: yarn build
      - name: Pin to IPFS on Pinata
        id: pinata
        uses: aquiladev/ipfs-action@04b43256a5b66e2023e237d48c84784a2ec298dd
        with:
          path: ./build
          pinName: 3cities ${{ needs.tag.outputs.new_tag }}
          service: pinata
          pinataKey: ${{ secrets.PINATA_API_KEY }}
          pinataSecret: ${{ secrets.PINATA_API_SECRET_KEY }}
      - name: Pin to IPFS on Infura
        id: infura
        uses: aquiladev/ipfs-action@04b43256a5b66e2023e237d48c84784a2ec298dd
        with:
          path: ./build
          pinName: 3cities ${{ needs.tag.outputs.new_tag }}
          service: infura
          infuraProjectId: ${{ secrets.INFURA_PROJECT_ID }}
          infuraProjectSecret: ${{ secrets.INFURA_PROJECT_SECRET }}
      - name: Convert CIDv0 to CIDv1
        id: convert-cidv0
        uses: uniswap/convert-cidv0-cidv1@v1.0.0
        with:
          cidv0: ${{ steps.pinata.outputs.hash }}
      - name: Update DNS with new IPFS hash
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          RECORD_DOMAIN: '3cities.xyz'
          RECORD_NAME: '_dnslink'
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        uses: textileio/cloudflare-update-dnslink@0fe7b7a1ffc865db3a4da9773f0f987447ad5848
        with:
          cid: ${{ steps.pinata.outputs.hash }}
      - name: Release
        uses: actions/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.tag.outputs.new_tag }}
          release_name: Release ${{ needs.tag.outputs.new_tag }}
          body: |
            IPFS hash of the deployment:
            - CIDv0: `${{ steps.pinata.outputs.hash }}`
            - CIDv1: `${{ steps.convert-cidv0.outputs.cidv1 }}`

            The latest release is always accessible via our alias to the Cloudflare IPFS gateway at [3cities.xyz](https://3cities.xyz).

            You can also access the 3cities interface directly from an IPFS gateway.
            **BEWARE**: the 3cities interface uses [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to remember your settings, such as which tokens you have imported.
            **You should always use an IPFS gateway that enforces origin separation**, or our alias to the latest release at [3cities.xyz](https://3cities.xyz).
            Your 3cities settings are never remembered across different URLs.

            IPFS gateways:
            - https://${{ steps.convert-cidv0.outputs.cidv1 }}.ipfs.dweb.link/
            - https://${{ steps.convert-cidv0.outputs.cidv1 }}.ipfs.cf-ipfs.com/
            - [ipfs://${{ steps.upload.outputs.hash }}/](ipfs://${{ steps.pinata.outputs.hash }}/)

            ${{ needs.tag.outputs.changelog }}
